# Generated by Django 2.2.11 on 2020-03-31 07:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp1', '0002_group_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'name': 'test'}),
        ),
        migrations.AddField(
            model_name='location',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'name': 'test'}),
        ),
        migrations.AddField(
            model_name='user',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'name': 'test'}),
        ),
    ]
